trigger:
  branches:
    include:
      - master
      - develop
    exclude:
      - migrate/efcore
  paths:
    exclude:
    - README.md
    - .gitignore
    - .vscode/*
    - pipeline/stack.destroy.pipeline.yaml


stages:

- stage: branch
  displayName: Branch Stage
  variables:
    stack: $(Build.SourceBranchName)
  jobs:
  - template: pipeline/infra.create.job.yaml
    parameters:
      jobName: infrastructure
  - template: pipeline/app.test.job.yaml
    parameters:
      jobName: apps
  - template: pipeline/app.deploy.job.yaml
    parameters:
      dependsOn: apps

- stage: deploy
  displayName: Deploy to Demo Envionment 
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - template: pipeline/deploymentjob.yaml
      parameters:
        jobName: demo_deploymentjob
        environment: demo

- stage: promote
  displayName: Promote in Demo Envionment (10%)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: init
      steps:
      - script: echo "Promoting in Demo"

    - template: pipeline/app.promote.deploymentjob.yaml
      parameters:
        dependsOn: init
        jobName: demo_promotejob_10
        environment: demo
        percent: "10"
    - job: delay1
      displayName: Delay
      pool: server
      dependsOn: demo_promotejob_10
      steps:
      - task: Delay@1
        inputs:
          delayForMinutes: '5' 
    - template: pipeline/app.promote.deploymentjob.yaml
      parameters:
        dependsOn: delay1
        jobName: demo_promotejob_50
        environment: demo
        percent: "50"
    - job: delay2
      displayName: Delay
      dependsOn: demo_promotejob_50
      pool: server
      steps:
      - task: Delay@1
        inputs:
          delayForMinutes: '5' 
    - template: pipeline/app.slotswap.deploymentjob.yaml
      parameters:
        dependsOn: delay2
        jobName: demo_swapslots
        environment: demo

    