trigger:
  branches:
    include:
    - master
    - develop

stages:
- stage: branch
  displayName: Branch Stage
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/')
  variables:
    stack: $(Build.SourceBranchName)
  jobs:
  - template: pipeline/infra.create.job.yaml
    parameters:
      jobName: infrastructure
  - template: pipeline/app.test.job.yaml
    parameters:
      jobName: apps
  - template: pipeline/app.deploy.job.yaml
    parameters:
      dependsOn: apps

- stage: deploy
  displayName: Deploy to Demo Envionment 
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  variables: 
    stack: demo
  jobs:
    - template: pipeline/deploymentjob.yaml
      parameters:
        jobName: demo_infrastructure
        environment: demo
