trigger:
  branches:
    include:
    - master
    - develop
  tags:
    include:
    - demo/*

stages:
- stage: branch
  displayName: Branch Stage
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
  jobs:
  - template: pipeline/infra.create.job.yaml
    parameters:
      jobName: infrastructure
  - template: pipeline/app.test.job.yaml
    parameters:
      jobName: apps
  - template: pipeline/app.deploy.job.yaml
    parameters:
      dependsOn: apps

- stage: test
  displayName: test
  jobs:
    - job: test
      steps:
        - script: echo $(Build.SourceBranch)

- stage: deploy
  displayName: Deploy to Demo Envionment 
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/demo/'))
  variables: 
    stack: demo
  jobs:
    - template: pipeline/infra.create.deployment.yaml
      parameters:
        jobName: infrastructure
        environment: demo
    - template: pipeline/app.deploy.deployment.yaml
      parameters:
        dependsOn: infrastructure
        environment: demo