trigger:
  branches:
    exclude:
    - '*'  # exclude always - should just trigger manually

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Pulumi xtellurian

steps:
  - script: |
      if [ "$(action)" == "up" ] || [ "$(action)" == "preview" ] || [ "$(action)" == "destroy" ]; then
          echo "$(action) is a valid Pulumi action"
      else
          echo "Action $(action) is invalid. Choose 'up' or 'destroy' "
      fi
    displayName: Check pulumi action is valid

  - script: curl -fsSL https://get.pulumi.com | sh
    condition: eq(variables['Build.Reason'], 'Manual')
    displayName: Install Pulumi 

  - script: npm install
    condition: eq(variables['Build.Reason'], 'Manual')
    workingDirectory: pulumi
    displayName: NPM install

  - task: Pulumi@0
    condition: eq(variables['Build.Reason'], 'Manual')
    inputs:
      azureSubscription: "amphoradata1"
      command: "$(action)"
      cwd: "pulumi/"
      stack: "xtellurian/amphora/test"