
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Pulumi xtellurian

steps:
  - script: npm install
    workingDirectory: pulumi
    displayName: NPM install
  - task: Pulumi@0
    condition: eq(variables['Build.Reason'], 'Manual')
    inputs:
      azureSubscription: "amphoradata1"
      command: "preview"
      cwd: "pulumi/"
      stack: "xtellurian/amphora/test"

  - task: Pulumi@0
    condition: eq(variables['Build.Reason'], 'Manual')
    inputs:
      azureSubscription: "amphoradata1"
      command: "up"
      cwd: "pulumi/"
      stack: "xtellurian/amphora/test"