config:
  acr:sku: Basic
  amphora:SendGridApiKey:
    secure: AAABAOeeviUNSEtmScuEbitizbMppi3bZ5J9DJJvLw/BMB5AAlysqczTaHTbFOPNaaZeaVsE8LWFMFTzVd4k5E5XIQgMMUkQ1y0deEDmlwRnjYkW9R1RRxl90byaxSTnixj+sbc=
  amphora:tokenManagement__secret:
    secure: AAABABnxOK+92zImVWcPhzKGyLnA73xKxu8szUC1MxWs5cZEqHiMxQESPJMobj9yZy3c4g==
  application:appSvcPlanSize: B1
  application:appSvcPlanTier: Basic
  azure:environment: public
  azure:subscriptionId: 651f2ed5-6e2f-41d0-b533-0cd28801ef2a
  azuresearch:sku: free
  auth:ids:
  - objectId: 16ab5eb9-f9e7-4df0-b40c-58ad0e0022d8
    name: rian
  - appId: 4a60dad9-8036-4ff5-9653-c38e6e89f303
    objectId: cd43f2d2-7e12-48fc-a856-713d04ab71ed
    name: sp
