config:
  amphora:tokenManagement__secret:
    secure: AAABABnxOK+92zImVWcPhzKGyLnA73xKxu8szUC1MxWs5cZEqHiMxQESPJMobj9yZy3c4g==
  application:acrSku: Basic
  application:appSvcPlanSize: B1
  application:appSvcPlanTier: Basic
  application:imageName: webapp
  authentication:rian: 16ab5eb9-f9e7-4df0-b40c-58ad0e0022d8
  authentication:spAppId: 4a60dad9-8036-4ff5-9653-c38e6e89f303
  authentication:spObjectId: cd43f2d2-7e12-48fc-a856-713d04ab71ed
  authentication:subscriptionId: 651f2ed5-6e2f-41d0-b533-0cd28801ef2a
  authentication:tenantId: 617bc365-674a-436e-8a27-5bacbe6df190
  azure:environment: public
  location:primary: AustraliaSoutheast
  location:secondary: AustraliaEast
