config:
  amphora:tokenManagement__secret:
    secure: AAABABnxOK+92zImVWcPhzKGyLnA73xKxu8szUC1MxWs5cZEqHiMxQESPJMobj9yZy3c4g==
  application:acrSku: Basic
  application:appSvcPlanSize: B1
  application:appSvcPlanTier: Basic
  azure:environment: public
  
