
parameters:
  jobName: 'deploy'
  dependsOn: 'apps'

jobs:
- job: ${{ parameters.jobName }}
  displayName: Deploy App
  dependsOn: 
    - ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'

  variables:
  - group: AzureDeploySP
  - name: acrName
    value: $[ dependencies.infrastructure.outputs['pulumi.acrName'] ]
  - name: webAppResourceId
    value: $[ dependencies.infrastructure.outputs['pulumi.webAppResourceId'] ]
  steps:
  - template: app.deploy.steps.yaml
