
parameters:
  jobName: 'swapslots'
  environment: ''
  dependsOn: ''

jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Swap Slots- ${{ parameters.jobName }}
  environment: ${{ parameters.environment }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
  - group: Pulumi xtellurian
  - name: stack
    value: ${{ parameters.environment }}

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
        - template: checkversion.steps.yaml
        - template: install.pulumi.steps.yaml
        - template: az-login.steps.yaml
        - script: |
            # Add the pulumi CLI to the PATH
            set -e
            export PATH=$PATH:$HOME/.pulumi/bin
            pushd infra
            . pulumi-stack.sh
            webAppId=$(pulumi stack output webAppResourceId)
            az webapp deployment slot swap  --ids $webAppId --slot staging --target-slot production
            az webapp traffic-routing set --distribution staging=0 --ids $webAppId
            az webapp config appsettings set --ids $webAppId -s staging --slot-settings STACK="$STACK(staging)"
            az webapp config appsettings set --ids $webAppId --slot-settings STACK="$STACK" #prod slot
            popd
          displayName: Swap Staging and Production
          env:
            PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
            ARM_CLIENT_ID: $(appId)
            ARM_CLIENT_SECRET: $(password)
            ARM_SUBSCRIPTION_ID: $(subscription)
            ARM_TENANT_ID: $(tenant)
            STACK: $(stack) 
            STAGING_PERCENT: $(percent)
            



