
parameters:
  jobName: 'swapslots'
  environment: ''

jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Promote to 50% - ${{ parameters.jobName }}
  environment: ${{ parameters.environment }}
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
  - group: AzureDeploySP
  - group: Pulumi xtellurian
  - name: stack
    value: ${{ parameters.environment }}

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
        - template: install.pulumi.steps.yaml
        - script: |
            # Add the pulumi CLI to the PATH
            set -e
            export PATH=$PATH:$HOME/.pulumi/bin
            pushd infra
            pulumi stack select $STACK
            webAppId=$(pulumi stack output webAppResourceId)
            # az webapp traffic-routing set --distribution staging=$STAGING_PERCENT --ids $webAppId
            az webapp deployment slot swap  --ids $webAppId --slot staging --target-slot production
            popd
          displayName: Swap Staging and Production
          env:
            PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
            ARM_CLIENT_ID: $(appId)
            ARM_CLIENT_SECRET: $(password)
            ARM_SUBSCRIPTION_ID: $(subscription)
            ARM_TENANT_ID: $(tenant)
            STACK: $(stack) 
            STAGING_PERCENT: $(percent)
            



