
parameters:
  jobName: 'deploy'
  dependsOn: 'apps'

jobs:
- job: ${{ parameters.jobName }}
  displayName: Deploy App
  dependsOn: 
    - infrastructure
    # - apps
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
  - group: AzureDeploySP
  - name: acrName
    value: $[ dependencies.infrastructure.outputs['pulumi.acrName'] ]
  - name: webAppResourceId
    value: $[ dependencies.infrastructure.outputs['pulumi.webAppResourceId'] ]
  steps:
  - script: echo acrName is $(acrName)
  - script: echo webAppResourceId is $(webAppResourceId)
  - template: app.deploy.steps.yaml
