
parameters:
  jobName: 'deploy'
  dependsOn: 'apps'
  environment: ''

jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Deploy App
  environment: ${{ parameters.environment }}
  dependsOn: 
    - infrastructure
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
  - group: AzureDeploySP
  - name: acrName
    value: $[ dependencies.infrastructure.outputs['pulumi.acrName'] ]
  - name: webAppResourceId
    value: $[ dependencies.infrastructure.outputs['pulumi.webAppResourceId'] ]

  strategy:
    runOnce:
      deploy:
        steps:
        - script: ls
        - template: app.deploy.steps.yaml