parameters:
  jobName: 'apps'

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: infrastructure
  strategy:
    matrix:
      InMemory:
        PersistentStores: ''
        disableKv: 'true'
      Persistent:
        PersistentStores: 'true'
        disableKv: ''
    maxParallel: 2
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    - group: AzureDeploySP
    - group: Pulumi xtellurian
    - name: buildConfiguration
      value: 'Release'

  steps:
    - template: install.pulumi.steps.yaml
    - script: |
        export PATH=$PATH:$HOME/.pulumi/bin
        pushd infra
        . pulumi-stack.sh
        export kvUri=$(pulumi stack output kvUri)
        echo PersistentStores - $(PersistentStores)
        echo kvUri - "$kvUri"
        if [ ! -z $(PersistentStores) ] && [ -z $kvUri ] ;
          then
                echo "PersistentStores is set, with no kvUri. Exiting with error"
                exit 1
          fi
      displayName: Check params set correctly
      env:
        STACK: $(stack)
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)

    # required to access KV in testing
    - script: az login --service-principal -u $NAME -p $PASSWORD --tenant $TENANT
      displayName: Az Login
      env: 
        NAME: $(name)
        PASSWORD: $(password)
        TENANT: $(tenant)

    - script: |
        export PATH=$PATH:$HOME/.pulumi/bin
        pushd infra
        . pulumi-stack.sh
        export kvUri=$(pulumi stack output kvUri)
        popd
        pushd apps
        docker-compose build test
        docker-compose run -e kvUri=$kvUri -e PersistentStores=$PersistentStores -e disableKv=$disableKv test
      displayName: Run Tests
      env:
        PersistentStores: $(PersistentStores)
        disableKv: $(disableKv)
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)

    - task: PublishTestResults@2
      condition: always() 
      inputs:
        testResultsFormat: 'xUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
        testRunner: VSTest
        testResultsFiles: '$(Build.SourcesDirectory)/apps/TestOutput.xml'

    - task: PublishCodeCoverageResults@1
      displayName: Publish Code Coverage Report
      inputs:
        summaryFileLocation: $(Build.SourcesDirectory)/apps/coverage.cobertura.xml
        codecoverageTool: cobertura