
parameters:
  jobName: 'deploy'
  staging: 'false'

jobs:
- job: ${{ parameters.jobName }}
  displayName: Deploy App
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: 
    - infrastructure
    - apps
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
    staging: ${{ parameters.staging }}
  steps:
  - template: app.deploy.steps.yaml
