
parameters:
  jobName: 'deploy'
  environment: ''

jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Create Infra and Deploy App - ${{ parameters.jobName }}
  environment: ${{ parameters.environment }}
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
  - group: AzureDeploySP

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
        - template: infra.create.steps.yaml
        - template: app.deploy.steps.yaml