
parameters:
  jobName: 'deploy'
  environment: ''
  staging: 'false'

jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Deployment - ${{ parameters.jobName }}
  environment: ${{ parameters.environment }}
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
  - group: AzureDeploySP
  - group: Pulumi xtellurian
  - name: stack
    value: ${{ parameters.environment }}
  - name: staging
    value: ${{ parameters.staging }}

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
          persistCredentials: true
        - template: infra.create.steps.yaml
        - template: app.deploy.steps.yaml
        - script: |
            git config user.email "AzureDevOps@amphoradata.com"
            git config user.name "Build Agent"
            git status
            TAG="$(Environment.Name)/$(Build.BuildId)"
            echo Tagging Branch with $TAG
            git tag -a $TAG -m "$(Build.Reason) requested for $(Build.RequestedFor)"
            git push origin $TAG
          displayName: Tag the source repository
