
parameters:
  jobName: 'deploy'
  environment: ''
  staging: 'false'

jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Deployment - ${{ parameters.jobName }}
  environment: ${{ parameters.environment }}
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
  - group: Pulumi xtellurian
  - name: stack
    value: ${{ parameters.environment }}
  - name: staging
    value: ${{ parameters.staging }}

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
          persistCredentials: true
        - template: infra.create.steps.yaml
        - template: app.deploy.steps.yaml
        - template: tagrepo.steps.yaml
          parameters:
            tag: $(Environment.Name)/$(Build.BuildId)
