
parameters:
  environment: ''
  staging: 'false'

jobs:
# Infra
- deployment: infrastructure
  displayName: Create Infrastructure
  environment: ${{ parameters.environment }}
  pool:
    vmImage: 'Ubuntu-16.04'

  variables:
  - group: Pulumi xtellurian
  - name: stack
    value: ${{ parameters.environment }}
  - name: staging
    value: ${{ parameters.staging }}

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
          persistCredentials: true
        - template: artifacts.download.steps.yaml
        - template: az-login.steps.yaml
        - template: install.pulumi.steps.yaml
        - template: infra.create.steps.yaml
        - template: app.deploy-container-image.steps.yaml
        - template: app.deploy-app-svc.steps.yaml
        # - template: app.deploy-k8s.steps.yaml

- template: k8s.deploymentjob.yaml
  parameters:
    environment: ${{ parameters.environment }}
