
##################################################################
#           Deploy Infrastructure
##################################################################

parameters:
  jobName: 'infrastructure'

jobs:
- job: ${{ parameters.jobName }}
  displayName: Infrastructure
  pool:
    vmImage: 'ubuntu-latest'
  variables:
  - group: Pulumi xtellurian
  - group: AzureDeploySP

  steps:
    - template: infra.create.steps.yaml
