
##################################################################
#           Deploy Infrastructure
##################################################################

parameters:
  jobName: 'infrastructure'
  environment: $(Build.SourceBranchName)

  strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment


jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Deploy to ${{ parameters.environment }}
  environment: ${{ parameters.environment }}
  pool:
    vmImage: 'ubuntu-latest'
  variables:
  - group: Pulumi xtellurian
  - group: AzureDeploySP

  strategy:
    runOnce:
      deploy:
        steps:
          - template: pipeline/infra.create.steps.yaml
