
##################################################################
#           Deploy Infrastructure
##################################################################

parameters:
  jobName: 'infrastructure'

jobs:
- job: ${{ parameters.jobName }}
  displayName: infrastructure
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian

  steps:
  - template: az-login.steps.yaml
  - template: infra.create.steps.yaml
