
##################################################################
#           Deploy Infrastructure
##################################################################

parameters:
  jobName: 'infrastructure'
  environment: ''


jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Deploy to ${{ parameters.environment }}
  environment: ${{ parameters.environment }}
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - group: AzureDeploySP

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
        - template: infra.create.steps.yaml
