
##################################################################
#           Deploy Infrastructure
##################################################################

parameters:
  jobName: 'infrastructure'
  environment: $(Build.SourceBranchName)


jobs:
- deployment: ${{ parameters.jobName }}
  displayName: Deploy to ${{ parameters.environment }}
  environment: ${{ parameters.environment }}
  pool:
    vmImage: 'ubuntu-latest'
  variables:
  - group: Pulumi xtellurian
  - group: AzureDeploySP

  strategy:
    runOnce:
      deploy:
        steps:
        - template: infra.create.steps.yaml
