
##################################################################
#           Deploy Infrastructure
##################################################################

parameters:
  jobName: 'infrastructure'
  environment: $(Build.SourceBranchName)

  strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment


jobs:
- job: ${{ parameters.jobName }}
  displayName: Deploy to ${{ parameters.environment }}
  pool:
    vmImage: 'ubuntu-latest'
  variables:
  - group: Pulumi xtellurian
  - group: AzureDeploySP

  steps:
    - template: infra.create.steps.yaml
