
##################################################################
#           Deploy Infrastructure
##################################################################

parameters:
  jobName: 'infrastructure'

jobs:
- job: ${{ parameters.jobName }}
  displayName: infrastructure
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian

  steps:
  - task: Delay@1
    displayName: Avoid conflict PRs and Branch Builds
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      delayForMinutes: '2'
  - template: az-login.steps.yaml
  - template: install.pulumi.steps.yaml
  - template: infra.create.steps.yaml
