# K8s Deployment

parameters:
  dependsOn: ''

jobs:
- job: primary
  displayName: Deployment - primary
  dependsOn:
    - ${{ parameters.dependsOn }}
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - name: region
    value: primary
  steps:
  - script: |
      if [ -z "$STACK" ]
      then
            echo "\$STACK is empty"
            exit 1
      else
            echo "\$STACK is NOT empty"
      fi
    env:
      STACK: $(stack)
  - template: install.pulumi.steps.yaml
  - template: app.deploy-k8s.steps.yaml

# secondary
- job: secondary
  displayName: Deployment - secondary
  dependsOn:
    - primary
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - name: region
    value: secondary
  steps:
  - script: |
      if [ -z "$STACK" ]
      then
            echo "\$STACK is empty"
            exit 1
      else
            echo "\$STACK is NOT empty"
      fi
    env:
      STACK: $(stack)
  - template: install.pulumi.steps.yaml
  - template: app.deploy-k8s.steps.yaml
