# K8s Deployment

parameters:
  environment: ''
  dependsOn: ''

jobs:
- job: ${{ parameters.environment }}_primary
  displayName: Deployment - ${{ parameters.environment }} - primary
  dependsOn:
    - ${{ parameters.dependsOn }}
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - name: stack
    value: ${{ parameters.environment }}
  - name: region
    value: primary
  steps:
  - template: install.pulumi.steps.yaml
  - template: app.deploy-k8s.steps.yaml

# secondary
- job: ${{ parameters.environment }}_secondary
  displayName: Deployment - ${{ parameters.environment }} - secondary
  dependsOn:
    - ${{ parameters.environment }}_primary
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - name: stack
    value: ${{ parameters.environment }}
  - name: region
    value: secondary
  steps:
  - template: install.pulumi.steps.yaml
  - template: app.deploy-k8s.steps.yaml
