# K8s Deployment

parameters:
  dependsOn: ''

jobs:
- job: australiasoutheast
  displayName: Deployment - australiasoutheast
  dependsOn:
    - ${{ parameters.dependsOn }}
    - infrastructure
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - name: region
    value: australiasoutheast
  - name: pulumi.acrName
    value: $[ dependencies.infrastructure.outputs['pulumi.acrName'] ]
  steps:
  - script: |
      if [ -z "$STACK" ]
      then
            echo "\$STACK is empty"
            exit 1
      else
            echo "\$STACK is NOT empty"
      fi
    env:
      STACK: $(stack)
  - template: install.pulumi.steps.yaml
  - template: app.deploy-k8s.steps.yaml

- job: australiaeast
  condition: false # TODO: renable secondary
  displayName: Deployment - australiaeast
  dependsOn:
    - australiasoutheast
    - infrastructure
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - name: region
    value: australiaeast
  - name: pulumi.acrName
    value: $[ dependencies.infrastructure.outputs['pulumi.acrName'] ]
  steps:
  - script: |
      if [ -z "$STACK" ]
      then
            echo "\$STACK is empty"
            exit 1
      else
            echo "\$STACK is NOT empty"
      fi
    env:
      STACK: $(stack)
  - template: install.pulumi.steps.yaml
  - template: app.deploy-k8s.steps.yaml
