# K8s Deployment

parameters:
- name: environment
  type: string
  default: develop
  values:
  - develop
  - master
  - prod
  
jobs:
- deployment: australiasoutheast
  displayName: Deployment - australiasoutheast
  environment: ${{ parameters.environment }}
  dependsOn:
    - infrastructure
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - name: region
    value: australiasoutheast
  - name: pulumi.acrName
    value: $[ dependencies.infrastructure.outputs['pulumi.acrName'] ]
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
          persistCredentials: true
        - template: artifacts.download.steps.yaml
        - template: install.pulumi.steps.yaml
        - template: app.deploy-k8s.steps.yaml

- deployment: australiaeast
  displayName: Deployment - australiaeast
  environment: ${{ parameters.environment }}
  dependsOn: 
    - australiasoutheast
    - infrastructure
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: Pulumi xtellurian
  - name: region
    value: australiaeast
  - name: pulumi.acrName
    value: $[ dependencies.infrastructure.outputs['pulumi.acrName'] ]
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self  # deployment job doesn't check it out
          persistCredentials: true
        - template: artifacts.download.steps.yaml
        - template: install.pulumi.steps.yaml
        - template: app.deploy-k8s.steps.yaml
