trigger:
  branches:
    exclude:
    - "*"

schedules:
- cron: "0 16 * * *"
  displayName: Daily 2am (AEST)
  branches:
    include:
    - master
    - develop

variables:
- group: Pulumi xtellurian
- group: AzureDeploySP

steps:
- script: |
    chmod +x ./infra/*.sh
    ./infra/setup.sh
    pulumi destroy --stack master
    pulumi destroy --stack develop
  displayName: 'Destroy master and develop stack'
  name: pulumi
  env:
    PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
    ARM_CLIENT_ID: $(appId)
    ARM_CLIENT_SECRET: $(password)
    ARM_SUBSCRIPTION_ID: $(subscription)
    ARM_TENANT_ID: $(tenant)
    STACK: $(stack) 




