trigger:
  branches:
    exclude:
    - "*"
    - refs/tags/*
    - refs/heads/*

schedules:
- cron: "0 13 * * *"
  displayName: Daily 11pm (AEST)
  branches:
    include:
    - master
  always: true # run even if there's no source changes

variables:
- group: Pulumi xtellurian
- group: AzureDeploySP

jobs:

  - job: destroy_develop_infra
    displayName: Destroy Develop Infrastructure
    steps:
    - template: install.pulumi.steps.yaml
    - template: az-login.steps.yaml
    - script: |
        export PATH=$PATH:$HOME/.pulumi/bin
        pushd infra
        npm install
        pulumi destroy -r -s develop -y
        popd
      displayName: Destroy Infrastructure
      name: destroy
      env:
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
        ARM_CLIENT_ID: $(appId)
        ARM_CLIENT_SECRET: $(password)
        ARM_SUBSCRIPTION_ID: $(subscription)
        ARM_TENANT_ID: $(tenant)
        STACK: $(stack) 

  - job: destroy_master_infra
    displayName: Destroy Master Infrastructure
    steps:
    - template: install.pulumi.steps.yaml
    - template: az-login.steps.yaml
    - script: |
        export PATH=$PATH:$HOME/.pulumi/bin
        pushd infra
        npm install
        pulumi destroy -r -s master -y
        popd
      displayName: Destroy Infrastructure
      name: destroy
      env:
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
        ARM_CLIENT_ID: $(appId)
        ARM_CLIENT_SECRET: $(password)
        ARM_SUBSCRIPTION_ID: $(subscription)
        ARM_TENANT_ID: $(tenant)
        STACK: $(stack) 
