trigger:
  branches:
    exclude:
    - "*"
    - refs/tags/*
    - refs/heads/*

schedules:
- cron: "0 13 * * *"
  displayName: Daily 11pm (AEST)
  branches:
    include:
    - master
  always: true # run even if there's no source changes

variables:
- group: Pulumi xtellurian
- group: AzureDeploySP

steps:
- template: install.pulumi.steps.yaml
- script: |
    export PATH=$PATH:$HOME/.pulumi/bin
    pushd infra
    pulumi destroy --stack master -y
    pulumi destroy --stack develop -y
    popd
  displayName: 'Destroy master and develop stack'
  name: destroy
  env:
    PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
    ARM_CLIENT_ID: $(appId)
    ARM_CLIENT_SECRET: $(password)
    ARM_SUBSCRIPTION_ID: $(subscription)
    ARM_TENANT_ID: $(tenant)
    STACK: $(stack) 




