# coding: utf-8

"""
    AmphoraApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Amphora(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'content_type': 'str',
        'title': 'str',
        'description': 'str',
        'price': 'float',
        'org_id': 'str',
        'id': 'str'
    }

    attribute_map = {
        'content_type': 'contentType',
        'title': 'title',
        'description': 'description',
        'price': 'price',
        'org_id': 'orgId',
        'id': 'id'
    }

    def __init__(self, content_type=None, title=None, description=None, price=None, org_id=None, id=None):  # noqa: E501
        """Amphora - a model defined in OpenAPI"""  # noqa: E501

        self._content_type = None
        self._title = None
        self._description = None
        self._price = None
        self._org_id = None
        self._id = None
        self.discriminator = None

        if content_type is not None:
            self.content_type = content_type
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if price is not None:
            self.price = price
        if org_id is not None:
            self.org_id = org_id
        if id is not None:
            self.id = id

    @property
    def content_type(self):
        """Gets the content_type of this Amphora.  # noqa: E501


        :return: The content_type of this Amphora.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this Amphora.


        :param content_type: The content_type of this Amphora.  # noqa: E501
        :type: str
        """

        self._content_type = content_type

    @property
    def title(self):
        """Gets the title of this Amphora.  # noqa: E501


        :return: The title of this Amphora.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Amphora.


        :param title: The title of this Amphora.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this Amphora.  # noqa: E501


        :return: The description of this Amphora.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Amphora.


        :param description: The description of this Amphora.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def price(self):
        """Gets the price of this Amphora.  # noqa: E501


        :return: The price of this Amphora.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this Amphora.


        :param price: The price of this Amphora.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def org_id(self):
        """Gets the org_id of this Amphora.  # noqa: E501


        :return: The org_id of this Amphora.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this Amphora.


        :param org_id: The org_id of this Amphora.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def id(self):
        """Gets the id of this Amphora.  # noqa: E501


        :return: The id of this Amphora.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Amphora.


        :param id: The id of this Amphora.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Amphora):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
