# coding: utf-8

"""
    AmphoraApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.amphora_schema_api import AmphoraSchemaApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAmphoraSchemaApi(unittest.TestCase):
    """AmphoraSchemaApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.amphora_schema_api.AmphoraSchemaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_schemas_id_json_schema_get(self):
        """Test case for api_schemas_id_json_schema_get

        """
        pass

    def test_api_schemas_json_schema_put(self):
        """Test case for api_schemas_json_schema_put

        """
        pass

    def test_api_schemas_put(self):
        """Test case for api_schemas_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
