# coding: utf-8

"""
    AmphoraApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.amphora_api import AmphoraApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAmphoraApi(unittest.TestCase):
    """AmphoraApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.amphora_api.AmphoraApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_amphorae_get(self):
        """Test case for api_amphorae_get

        """
        pass

    def test_api_amphorae_id_drink_get(self):
        """Test case for api_amphorae_id_drink_get

        """
        pass

    def test_api_amphorae_id_fill_post(self):
        """Test case for api_amphorae_id_fill_post

        """
        pass

    def test_api_amphorae_id_get(self):
        """Test case for api_amphorae_id_get

        """
        pass

    def test_api_amphorae_put(self):
        """Test case for api_amphorae_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
