# coding: utf-8

"""
    AmphoraApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.schema import Schema  # noqa: E501
from openapi_client.rest import ApiException


class TestSchema(unittest.TestCase):
    """Schema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchema(self):
        """Test Schema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.schema.Schema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
