version: "3"
services:
  web:
    build: .
  genpy:
    image: openapitools/openapi-generator-cli
    depends_on: 
      - web
    volumes: 
      - ${PWD}/api-clients:/local
    command: generate -i http://web/swagger/v1/swagger.json -g python -o /local/python

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: dotnet test -l:trx;LogFileName=/output/TestOutput.xml /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=/output/
    volumes:
      - ./:/output
    environment: 
      RACK_ENV: development

